"""
Weekly summary email report.
"""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from config.settings import (
    EMAIL_FROM,
    EMAIL_PASSWORD,
    EMAIL_RECIPIENTS,
    EMAIL_SMTP_HOST,
    EMAIL_SMTP_PORT,
    EMAIL_USERNAME,
)

logger = logging.getLogger(__name__)


def send_email_report(
    brand_name: str,
    report: dict[str, Any],
    subject: str | None = None,
) -> bool:
    """Send a brand intelligence report via email."""
    if not EMAIL_RECIPIENTS or not EMAIL_USERNAME:
        logger.warning("Email not configured, skipping report")
        return False

    if subject is None:
        subject = f"Brand Intelligence Report: {brand_name}"

    # Build HTML body
    html = _build_html_report(brand_name, report)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = EMAIL_FROM or EMAIL_USERNAME
    msg["To"] = ", ".join(EMAIL_RECIPIENTS)
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(EMAIL_SMTP_HOST, EMAIL_SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_USERNAME, EMAIL_PASSWORD)
            server.send_message(msg)
            logger.info("Email report sent for %s", brand_name)
            return True
    except Exception:
        logger.exception("Failed to send email report")
        return False


def _build_html_report(brand_name: str, report: dict[str, Any]) -> str:
    severity = report.get("severity_summary", {})
    themes = report.get("themes", [])
    risks = report.get("risks", [])

    themes_html = "".join(
        f"<li><b>{t.get('name', '')}</b>: {t.get('description', '')} "
        f"({t.get('mention_count', 0)} mentions, sentiment: {t.get('avg_sentiment', 0):.2f})</li>"
        for t in themes
    )

    risks_html = "".join(
        f"<li><b>[{r.get('severity', '')}]</b> {r.get('title', '')}: {r.get('description', '')}</li>"
        for r in risks
    )

    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
        <h1>Brand Intelligence: {brand_name}</h1>

        <h2>Severity Overview</h2>
        <table border="1" cellpadding="8" cellspacing="0">
            <tr><td>Critical</td><td>{severity.get('critical', 0)}</td></tr>
            <tr><td>High</td><td>{severity.get('high', 0)}</td></tr>
            <tr><td>Medium</td><td>{severity.get('medium', 0)}</td></tr>
            <tr><td>Low</td><td>{severity.get('low', 0)}</td></tr>
        </table>

        <h2>Key Themes</h2>
        <ul>{themes_html or '<li>No themes detected</li>'}</ul>

        <h2>Risks</h2>
        <ul>{risks_html or '<li>No risks detected</li>'}</ul>

        <p style="color: #888; font-size: 12px;">
            Generated by Brand Management Tool
        </p>
    </body>
    </html>
    """
